# Generated by Django 4.2 on 2026-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='candidates.candidate'),
        ),
    ]
