# Generated by Django 4.2 on 2026-06-13 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('raw_resume_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('experience_years', models.FloatField(default=0)),
                ('certifications', models.JSONField(default=list)),
                ('resume_score', models.FloatField(default=0)),
                ('job_matches', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
