# Generated by Django 4.2 on 2026-06-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_skills', models.JSONField(default=list)),
                ('matched_skills', models.JSONField(default=list)),
                ('readiness_score', models.FloatField(default=0)),
                ('recommended_path', models.JSONField(default=list)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='CandidateJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('certification_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('match_percentage', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
